### ISSUE TITLE
Fix android aar build

### ISSUE THREAD

**Issue by ortex** [roc-project/roc-java#16]
Built aar doesn't work
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libroc.so.0.1" not found
    at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
    at java.lang.System.loadLibrary(System.java:1667)
    at com.github.rocproject.roc.RocLibrary.loadLibrary(RocLibrary.java:5)
    at com.github.rocproject.roc.ChannelSet.<init>(ChannelSet.java:18)
    at com.github.rocproject.roc.ChannelSet.<clinit>(ChannelSet.java:14)
```
how to build:
```
export JAVA_VERSION=8 
export ANDROID_API=28 
export ANDROID_BUILD_TOOLS_VERSION=28.0.3 
export ANDROID_NDK_VERSION=21.1.6352462 
export ROC_BASE_DIR=$HOME/roc-build

./scripts/travis/android/install.sh 
./scripts/travis/android/script.sh 
```

how to reproduce:
* clone https://github.com/roc-project/roc-droid
* replace https://github.com/roc-project/roc-droid/blob/master/app/libs/roc-android-release.aar with android/roc-android/build/outputs/aar/roc-android-release.aar
* try run app and click start

**Comment by gavv** [comment]
Note: ironically, soname and symlink feature was first introduced specifically for Android port: https://github.com/roc-project/roc/issues/222#issuecomment-502671429

**Comment by MatteoArella** [comment]
Yes gradle plugin doesn't pack shared libraries with extensions that differ from `.so` so `libroc.so.0.1` file won't be packed inside aar.
I've fixed setting `LDFLAGS="-Wl,-soname,libroc.so"` before building roc library with `scons`
